services:
  acacia_app:
    build: .
    command: sh -c "uvicorn src.main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src